[pytest]
markers =
    ui: UI тесты
    api: API тесты
    smoke: Smoke тесты
    positive: Позитивные тесты
    negative: Негативные тесты
    
addopts = 
    -v
    --strict-markers
    
python_files = test_*.py
python_classes = Test*
python_functions = test_*
